name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-manifest:
    uses: majksa-actions/workflows/.github/workflows/create-deployment-manifest.yml@v1
    strategy:
      matrix:
        environment: ["prod", "dev"]
    with:
      environment: ${{ matrix.environment }}
