name: Test

on:
  push:
    branches:
      - main

jobs:
  config:
    name: Config Server
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    env:
      MAIN_BRANCH: main
      ENV_BRANCH: env
    strategy:
      matrix:
        environment: ["prod"]
    steps:
      - name: Precheck
        id: precheck
        run: |
          echo "base_ref_name=env/${{ matrix.environment }}" >> $GITHUB_OUTPUT

      - name: Checkout ${{ env.MAIN_BRANCH }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.MAIN_BRANCH }}

      - name: Checkout ${{ env.ENV_BRANCH }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.ENV_BRANCH }}
          ref: ${{ steps.precheck.outputs.base_ref_name }}

      - name: Config Server
        uses: majksa-actions/deployment-config@v1
        with:
          source: ${{ env.MAIN_BRANCH }}/input
          target: ${{ env.ENV_BRANCH }}
          environment: ${{ matrix.environment }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{ format('Update {0} environment branch', steps.precheck.outputs.base_ref_name) }}
          commit-message: "chore: update environment branch data"
          body: "Updated manifest file"
          base: ${{ steps.precheck.outputs.base_ref_name }}
          branch: update/${{ steps.precheck.outputs.base_ref_name }}
          path: ${{ env.ENV_BRANCH }}
          delete-branch: true
          labels: bot,dist
