name: Test

on:
  push:
    branches:
      - main

jobs:
  config:
    name: Config Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config Server
        uses: majksa-actions/deployment-config@v1
        with:
          source: ./input
          target: ./output
          environment: prod

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "chore(target): update target/ on ${{ github.ref_name }}"
          commit-message: "chore(target): update target/"
          body: "Updated target/ built distributable files"
          branch: update-target--${{ github.ref_name }}
          delete-branch: true
          labels: bot,dist
